declare
    l_event_id number;
    l_venue_id number;
    l_xml xmltype;
begin

    l_venue_id := events_api.get_venue_id(p_venue_name => 'The Pink Pony Revue');
    l_event_id := events_api.get_event_id(p_venue_id => l_venue_id, p_event_name => 'Evangeline Thorpe');
    
    l_xml := events_xml_api.get_ticket_assignments(p_event_id => l_event_id, p_formatted => true);

    dbms_output.put_line(l_xml.getclobval());

end;

/*
<event_ticket_assignment>
  <event>
    <venue>
      <venue_id>21</venue_id>
      <venue_name>The Pink Pony Revue</venue_name>
      <organizer_email>Julia.Stein@ThePinkPonyRevue.com</organizer_email>
      <organizer_name>Julia Stein</organizer_name>
    </venue>
    <event_id>561</event_id>
    <event_name>Evangeline Thorpe</event_name>
    <event_date>2023-05-01</event_date>
    <event_tickets_available>200</event_tickets_available>
  </event>
  <ticket_resellers>
    <reseller>
      <reseller_id>21</reseller_id>
      <reseller_name>New Wave Tickets</reseller_name>
      <reseller_email>ticket.sales@NewWaveTickets.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>1</reseller_id>
      <reseller_name>Events For You</reseller_name>
      <reseller_email>ticket.sales@EventsForYou.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>2</reseller_id>
      <reseller_name>MaxTix</reseller_name>
      <reseller_email>ticket.sales@MaxTix.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>3</reseller_id>
      <reseller_name>Old School</reseller_name>
      <reseller_email>ticket.sales@OldSchool.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>4</reseller_id>
      <reseller_name>Source Tix</reseller_name>
      <reseller_email>ticket.sales@SourceTix.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>5</reseller_id>
      <reseller_name>The Source</reseller_name>
      <reseller_email>ticket.sales@TheSource.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>6</reseller_id>
      <reseller_name>Ticket Supply</reseller_name>
      <reseller_email>ticket.sales@TicketSupply.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>7</reseller_id>
      <reseller_name>Ticket Time</reseller_name>
      <reseller_email>ticket.sales@TicketTime.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>8</reseller_id>
      <reseller_name>Ticketron</reseller_name>
      <reseller_email>ticket.sales@Ticketron.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>9</reseller_id>
      <reseller_name>Tickets 2 Go</reseller_name>
      <reseller_email>ticket.sales@Tickets2Go.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>10</reseller_id>
      <reseller_name>Tickets R Us</reseller_name>
      <reseller_email>ticket.sales@TicketsRUs.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>11</reseller_id>
      <reseller_name>Your Ticket Supplier</reseller_name>
      <reseller_email>ticket.sales@YourTicketSupplier.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
    <reseller>
      <reseller_id>12</reseller_id>
      <reseller_name>Easy Tickets</reseller_name>
      <reseller_email>ticket.sales@EasyTickets.com</reseller_email>
      <ticket_assignments>
        <ticket_group>
          <ticket_group_id>2281</ticket_group_id>
          <price_category>SPONSOR</price_category>
          <price>120</price>
          <tickets_in_group>30</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>30</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2282</ticket_group_id>
          <price_category>VIP</price_category>
          <price>85</price>
          <tickets_in_group>70</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>70</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
        <ticket_group>
          <ticket_group_id>2283</ticket_group_id>
          <price_category>GENERAL ADMISSION</price_category>
          <price>42</price>
          <tickets_in_group>100</tickets_in_group>
          <tickets_assigned>0</tickets_assigned>
          <ticket_assignment_id>0</ticket_assignment_id>
          <assigned_to_others>0</assigned_to_others>
          <max_available>100</max_available>
          <min_assignment>0</min_assignment>
          <sold_by_reseller>0</sold_by_reseller>
          <sold_by_venue>0</sold_by_venue>
        </ticket_group>
      </ticket_assignments>
    </reseller>
  </ticket_resellers>
</event_ticket_assignment>
*/