ALTER TABLE EVENT_SYSTEM.ERROR_LOG MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.CUSTOMER_PURCHASES_MV MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.VENUES MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.RESELLERS MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.CUSTOMERS MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.EVENTS MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.TICKET_GROUPS MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.TICKET_ASSIGNMENTS MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.TICKET_SALES MOVE TABLESPACE EVENT_DATA
ALTER TABLE EVENT_SYSTEM.TICKETS MOVE TABLESPACE EVENT_DATA


PL/SQL procedure successfully completed.

